services:
  postgres:
    image: postgres:16
    container_name: nexusai-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: nexusai
      POSTGRES_PASSWORD: nexusai_password
      POSTGRES_DB: nexusai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: